# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=1000, verbose_name='content')),
            ],
            options={
                'verbose_name_plural': 'labels',
                'verbose_name': 'label',
            },
        ),
    ]
