# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('training_mode', models.BooleanField(default=1)),
                ('quiz_list', models.ManyToManyField(blank=True, related_name='quiz_list', to='quiz.Quiz', verbose_name='quiz_list')),
                ('task_list', models.ManyToManyField(blank=True, related_name='task_list', to='task.Task', verbose_name='task_list')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
