# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 01:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('category', 'creator')]),
        ),
    ]
