# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170815_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postresponse',
            name='label',
        ),
        migrations.RemoveField(
            model_name='postresponse',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postresponse',
            name='responder',
        ),
        migrations.DeleteModel(
            name='PostResponse',
        ),
    ]
