# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_auto_20170813_2113'),
        ('label', '0002_remove_label_post'),
        ('post', '0002_postresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('instruction', models.TextField(blank=True, verbose_name='instruction')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('label_list', models.ManyToManyField(to='label.Label', verbose_name='label list')),
                ('post_list', models.ManyToManyField(blank=True, default=None, to='post.Post', verbose_name='post list')),
                ('prerequisite', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='prerequisite')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
