# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 19:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'answers',
                'verbose_name': 'answer',
            },
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'answer keys',
                'verbose_name': 'answer key',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('max_posts', models.PositiveIntegerField(blank=True, null=True, verbose_name='max posts')),
                ('pass_mark', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='pass mark')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('label_list', models.ManyToManyField(to='label.Label', verbose_name='label list')),
                ('post_list', models.ManyToManyField(blank=True, default=None, to='post.Post', verbose_name='post list')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'verbose_name': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='quiz')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='responder')),
            ],
            options={
                'verbose_name_plural': 'quiz responses',
                'verbose_name': 'quiz response',
            },
        ),
        migrations.AddField(
            model_name='answerkey',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.AnswerKey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.Label'),
        ),
        migrations.AddField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
