# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170813_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.AnswerKey'),
        ),
    ]
